name: Publish

on:
  push:
    branches: [main]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm install
      - name: Setup git username
        run: git config user.name ${{ secrets.GIT_USERNAME }}
      - name: Setup git email
        run: git config user.email ${{ secrets.GIT_EMAIL }}
      - name: Setup .npmrc file
        run: npm ci
      - name: Format code
        run: npm run format
      - name: Build
        run: npm run build
      - name: Patch version
        run: npm version patch
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Update main branch
        run: git push
      - name: Checkout to dev branch
        run: git checkout dev
      - name: Merge main branch into dev
        run: git merge main
      - name: Update dev branch
        run: git push
